// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puvdlmdwnxgwjgvjhuwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1dmRsbWR3bnhnd2pndmpodXdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzU0MDYsImV4cCI6MjA2NTUxMTQwNn0.UR5ac44Gf446yNE7vlb6FDbwocGnwDi4D4ZW7h5XLs8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);